last0_root: /home/robot/zhy/last0
model_root: /home/robot/weights/MyData_finetune_last0_checkpoint-13-171570/tfmr
stats_path: null
device: cuda
cuda_id: 0
action_chunk: 16
latent_size: 8
use_latent: true
use_proprio: false
seed: 42
