#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from galaxea_fm.last0 import Last0ActionAdapter, Last0RobotState


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert LaST0 first action into Galaxea pose targets.")
    parser.add_argument("--observation_json", required=True, help="Observation JSON with robot_state.")
    parser.add_argument("--action_json", required=True, help="Result JSON generated by last0_server_inference.py.")
    parser.add_argument("--save_result_json", default=None, help="Optional output path.")
    parser.add_argument("--max_position_delta_m", type=float, default=0.03)
    parser.add_argument("--max_rotation_delta_rad", type=float, default=0.15)
    parser.add_argument("--no_clip", action="store_true")
    args = parser.parse_args()

    with open(args.observation_json, "r", encoding="utf-8") as handle:
        observation_payload = json.load(handle)
    if "robot_state" not in observation_payload:
        raise SystemExit("Observation JSON must include robot_state for pose target conversion.")
    robot_state = Last0RobotState.from_dict(observation_payload["robot_state"])

    with open(args.action_json, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    first_action = payload["first_action"]

    adapter = Last0ActionAdapter(
        max_position_delta_m=args.max_position_delta_m,
        max_rotation_delta_rad=args.max_rotation_delta_rad,
    )
    pose_command = adapter.adapt(first_action, robot_state, clip=not args.no_clip)
    serializable = pose_command.to_serializable()

    print(json.dumps(serializable, ensure_ascii=False, indent=2))
    if args.save_result_json:
        out_path = Path(args.save_result_json)
        out_path.write_text(json.dumps(serializable, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Saved pose command JSON to: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
